#include <windows.h>
#include <string>
#include <map>

namespace KeystrokeAutomation {
    std::map<std::string, WORD> virtualKeyMap = {
        {"lmouse", VK_LBUTTON},
        {"rmouse", VK_RBUTTON},
        {"mmouse", VK_MBUTTON},
        {"xmouse1", VK_XBUTTON1},
        {"xmouse2", VK_XBUTTON2},

        {"enter", VK_RETURN},
        {"space", VK_SPACE},
        {"ctrl", VK_CONTROL},
        {"lctrl", VK_LCONTROL},
        {"rctrl", VK_RCONTROL},
        {"alt", VK_MENU},
        {"lalt", VK_LMENU},
        {"ralt", VK_RMENU},
        {"shift", VK_SHIFT},
        {"lshift", VK_LSHIFT},
        {"rshift", VK_RSHIFT},
        {"lwin", VK_LWIN},
        {"rwin", VK_RWIN},
        {"apps", VK_APPS},
        {"esc", VK_ESCAPE},
        {"tab", VK_TAB},
        {"backspace", VK_BACK},
        {"capslock", VK_CAPITAL},

        {"up", VK_UP},
        {"down", VK_DOWN},
        {"left", VK_LEFT},
        {"right", VK_RIGHT},
        {"home", VK_HOME},
        {"end", VK_END},
        {"pgup", VK_PRIOR},
        {"pgdn", VK_NEXT},
        {"insert", VK_INSERT},
        {"del", VK_DELETE},

        {"f1", VK_F1},
        {"f2", VK_F2},
        {"f3", VK_F3},
        {"f4", VK_F4},
        {"f5", VK_F5},
        {"f6", VK_F6},
        {"f7", VK_F7},
        {"f8", VK_F8},
        {"f9", VK_F9},
        {"f10", VK_F10},
        {"f11", VK_F11},
        {"f12", VK_F12},
        {"f13", VK_F13},
        {"f14", VK_F14},
        {"f15", VK_F15},
        {"f16", VK_F16},
        {"f17", VK_F17},
        {"f18", VK_F18},
        {"f19", VK_F19},
        {"f20", VK_F20},
        {"f21", VK_F21},
        {"f22", VK_F22},
        {"f23", VK_F23},
        {"f24", VK_F24},

        {"num0", VK_NUMPAD0},
        {"num1", VK_NUMPAD1},
        {"num2", VK_NUMPAD2},
        {"num3", VK_NUMPAD3},
        {"num4", VK_NUMPAD4},
        {"num5", VK_NUMPAD5},
        {"num6", VK_NUMPAD6},
        {"num7", VK_NUMPAD7},
        {"num8", VK_NUMPAD8},
        {"num9", VK_NUMPAD9},
        {"add", VK_ADD},
        {"sub", VK_SUBTRACT},
        {"mul", VK_MULTIPLY},
        {"div", VK_DIVIDE},
        {"numdec", VK_DECIMAL},
        {"numlock", VK_NUMLOCK},

        {"prtscr", VK_SNAPSHOT},
        {"scrolllock", VK_SCROLL},
        {"pause", VK_PAUSE},

        {"a", 'A'},
        {"b", 'B'},
        {"c", 'C'},
        {"d", 'D'},
        {"e", 'E'},
        {"f", 'F'},
        {"g", 'G'},
        {"h", 'H'},
        {"i", 'I'},
        {"j", 'J'},
        {"k", 'K'},
        {"l", 'L'},
        {"m", 'M'},
        {"n", 'N'},
        {"o", 'O'},
        {"p", 'P'},
        {"q", 'Q'},
        {"r", 'R'},
        {"s", 'S'},
        {"t", 'T'},
        {"u", 'U'},
        {"v", 'V'},
        {"w", 'W'},
        {"x", 'X'},
        {"y", 'Y'},
        {"z", 'Z'},

        {"0", '0'},
        {"1", '1'},
        {"2", '2'},
        {"3", '3'},
        {"4", '4'},
        {"5", '5'},
        {"6", '6'},
        {"7", '7'},
        {"8", '8'},
        {"9", '9'}
    };
}